name: Update Docker image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Login to Docker
        uses: docker/login-action@v1
        with:
          username: trishan9
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
          registry: docker.io

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        # Set up Docker Buildx for building multi-platform images or using advanced features

      - name: Build and push server image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./server/Dockerfile
          push: true
          tags: trishan9/url-shortener:latest

      - name: Build and push discord bot image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./discord-bot/Dockerfile
          push: true
          tags: trishan9/url-shortener-bot:latest
